In [3]:
import numpy as np

In [16]:
import pandas as pd

In [17]:
data = pd.read_csv("training_diabetes_x_y_train.csv")

In [18]:
data.head(5)

# age       sex       bmi        bp        s1        s2        s3  \
0 -0.049105 -0.044642  0.160855 -0.046985 -0.029088 -0.019790 -0.047082   
1 -0.070900  0.050680 -0.089197 -0.074528 -0.042848 -0.025739 -0.032356   
2  0.001751 -0.044642 -0.070875 -0.022885 -0.001569 -0.001001  0.026550   
3  0.048974  0.050680  0.081097  0.021872  0.043837  0.064134 -0.054446   
4  0.041708  0.050680  0.061696 -0.040099 -0.013953  0.006202 -0.028674   

         s4        s5        s6      Y  
0  0.034309  0.028017  0.011349  346.0  
1 -0.002592 -0.012908 -0.054925  104.0  
2 -0.039493 -0.022512  0.007207   49.0  
3  0.071210  0.032433  0.048628  180.0  
4 -0.002592 -0.014956  0.011349  110.0

In [20]:
data.shape

(331, 11)

In [28]:
data.describe()

# age         sex         bmi          bp          s1          s2  \
count  331.000000  331.000000  331.000000  331.000000  331.000000  331.000000   
mean    -0.000214   -0.000293    0.000053   -0.001045   -0.001423   -0.001220   
std      0.047207    0.047618    0.048627    0.047621    0.047371    0.046936   
min     -0.107226   -0.044642   -0.090275   -0.102071   -0.126781   -0.115613   
25%     -0.034575   -0.044642   -0.035307   -0.036656   -0.035968   -0.029967   
50%      0.005383   -0.044642   -0.008362   -0.005671   -0.004321   -0.004445   
75%      0.038076    0.050680    0.030979    0.032775    0.027326    0.028905   
max      0.110727    0.050680    0.170555    0.132044    0.153914    0.198788   

               s3          s4          s5          s6           Y  
count  331.000000  331.000000  331.000000  331.000000  331.000000  
mean     0.000440   -0.001473   -0.001594    0.000099  149.722054  
std      0.047303    0.046591    0.048088    0.047263   76.796907  
min     -0.102307   -0.076395   -0.126097   -0.137767   25.000000  
25%     -0.032356   -0.039493   -0.035817   -0.034215   84.000000  
50%     -0.006584   -0.002592   -0.005145   -0.001078  138.000000  
75%      0.026550    0.034309    0.032124    0.027917  202.000000  
max      0.181179    0.185234    0.133599    0.135612  346.000000

In [38]:
type(data)

pandas.core.frame.DataFrame

In [41]:
data.dtypes

# age    float64
sex      float64
bmi      float64
bp       float64
s1       float64
s2       float64
s3       float64
s4       float64
s5       float64
s6       float64
Y        float64
dtype: object

In [44]:
x_train = data.iloc[:, 0:10]
x_train

# age       sex       bmi        bp        s1        s2        s3  \
0   -0.049105 -0.044642  0.160855 -0.046985 -0.029088 -0.019790 -0.047082   
1   -0.070900  0.050680 -0.089197 -0.074528 -0.042848 -0.025739 -0.032356   
2    0.001751 -0.044642 -0.070875 -0.022885 -0.001569 -0.001001  0.026550   
3    0.048974  0.050680  0.081097  0.021872  0.043837  0.064134 -0.054446   
4    0.041708  0.050680  0.061696 -0.040099 -0.013953  0.006202 -0.028674   
..        ...       ...       ...       ...       ...       ...       ...   
326  0.012648 -0.044642 -0.020218 -0.015999  0.012191  0.021233 -0.076536   
327  0.019913 -0.044642 -0.057941 -0.057314 -0.001569 -0.012587  0.074412   
328  0.023546 -0.044642  0.070319  0.025315 -0.034592 -0.014466 -0.032356   
329  0.016281  0.050680  0.072474  0.076958 -0.008449  0.005575 -0.006584   
330 -0.009147  0.050680 -0.030996 -0.026328 -0.011201 -0.001001 -0.021311   

           s4        s5        s6  
0    0.034309  0.028017  0.011349  
1   -0.002592 -0.012908 -0.054925  
2   -0.039493 -0.022512  0.007207  
3    0.071210  0.032433  0.048628  
4   -0.002592 -0.014956  0.011349  
..        ...       ...       ...  
326  0.108111  0.059881 -0.021788  
327 -0.039493 -0.061177 -0.075636  
328 -0.002592 -0.019197 -0.009362  
329 -0.002592 -0.023645  0.061054  
330 -0.002592  0.006209  0.027917  

[331 rows x 10 columns]

In [46]:
y_train = data.iloc[:, 10:11]
y_train

Y
0    346.0
1    104.0
2     49.0
3    180.0
4    110.0
..     ...
326  233.0
327   63.0
328  288.0
329  131.0
330   42.0

[331 rows x 1 columns]

In [48]:
from sklearn.linear_model import LinearRegression
alg1 = LinearRegression()

In [49]:
alg1.fit(x_train, y_train)

LinearRegression()

In [52]:
data2 = pd.read_csv("test_diabetes_x_test.csv")
data2.shape

(110, 10)

In [55]:
x_test=data2.iloc[:, 0:11]
x_test

0.02354575262934580082  0.05068011873981870252  -0.03746250427835440266  \
0                 -0.078165               -0.044642                -0.073030   
1                 -0.030942                0.050680                 0.001339   
2                 -0.005515                0.050680                 0.001339   
3                 -0.020045               -0.044642                -0.084886   
4                 -0.034575               -0.044642                -0.037463   
..                      ...                     ...                      ...   
105                0.009016                0.050680                 0.069241   
106                0.005383               -0.044642                 0.049840   
107                0.009016               -0.044642                -0.012673   
108                0.019913               -0.044642                -0.034229   
109                0.016281                0.050680                 0.009961   

     -0.04698505887976939938  -0.09100589560328480043  \
0                  -0.057314                -0.084126   
1                  -0.005671                 0.064477   
2                  -0.084857                -0.011201   
3                  -0.026328                -0.035968   
4                  -0.060757                 0.020446   
..                       ...                      ...   
105                 0.059744                 0.017694   
106                 0.097616                -0.015328   
107                 0.028758                -0.018080   
108                 0.055153                 0.067229   
109                -0.043542                -0.096510   

     -0.07553006287033779687  -0.03235593223976569732  \
0                  -0.074277                -0.024993   
1                   0.049416                -0.047082   
2                  -0.016658                 0.048640   
3                  -0.034194                 0.041277   
4                   0.043466                -0.013948   
..                       ...                      ...   
105                -0.023234                -0.047082   
106                -0.016345                -0.006584   
107                -0.005072                -0.047082   
108                 0.074155                -0.006584   
109                -0.094632                -0.039719   

     -0.03949338287409189657  -0.03075120986455629965  -0.01350401824497050006  
0                  -0.039493                -0.018118                -0.083920  
1                   0.108111                 0.083797                 0.003064  
2                  -0.039493                -0.041180                -0.088062  
3                  -0.051671                -0.082381                -0.046641  
4                  -0.002592                -0.030751                -0.071494  
..                       ...                      ...                      ...  
105                 0.034309                 0.103292                 0.073480  
106                -0.002592                 0.017037                -0.013504  
107                 0.034309                 0.023375                -0.005220  
108                 0.032833                 0.024725                 0.069338  
109                -0.039493                 0.017037                 0.007207  

[110 rows x 10 columns]

In [71]:
y_pred = alg1.predict(x_test)
y_pred

array([[105.8039198 ],
       [178.60857225],
       [ 79.3828781 ],
       [ 52.95868706],
       [ 98.87263854],
       [150.71755448],
       [ 34.86515216],
       [113.13535727],
       [161.50184038],
       [135.8615611 ],
       [ 94.71592222],
       [138.48094422],
       [141.37441723],
       [158.76862662],
       [171.65288616],
       [106.44835654],
       [103.92659639],
       [ 95.38693889],
       [167.40118092],
       [166.53426278],
       [101.53464712],
       [252.45035972],
       [147.02258547],
       [214.78906632],
       [161.27557106],
       [210.61315228],
       [ 71.78091585],
       [189.65032431],
       [206.6134259 ],
       [219.98643455],
       [168.80192534],
       [116.84846127],
       [178.74399639],
       [ 77.03247418],
       [ 59.54633214],
       [111.5673781 ],
       [156.95186739],
       [154.59591259],
       [198.94457493],
       [115.53884017],
       [153.46699024],
       [ 84.96179518],
       [113.70337192],
       [142

In [73]:
m = alg1.coef_[0]
c = alg1.intercept_
(m, c)

(array([  21.73408096, -256.66866675,  569.60940087,  303.63233545,
        -833.11088526,  525.74313633,  136.07129167,  140.89458927,
         731.44498492,   53.32119133]),
 array([150.70257489]))

In [82]:
np.savetxt(r"C:\Users\aryac\notebook materials\diabetes_prediction.csv", y_pred, delimiter=",")