In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [36]:
data = pd.read_csv("0000000000002429_training_titanic_x_y_train.csv")
val = data.Age.mean()
data.Age = data.Age.fillna(val)
x_train = data.iloc[:, [3, 4, 5]].values
y_train = data.iloc[:, 10].values
x_train

array([[29.       ,  1.       ,  0.       ],
       [29.7005597,  0.       ,  0.       ],
       [39.       ,  0.       ,  0.       ],
       ...,
       [32.       ,  0.       ,  0.       ],
       [22.       ,  0.       ,  0.       ],
       [29.7005597,  1.       ,  0.       ]])

In [37]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(x_train, y_train)

LogisticRegression()

In [38]:
testdata = pd.read_csv("0000000000002429_test_titanic_x_test.csv")
val2 = testdata.Age.mean()
testdata.Age = testdata.Age.fillna(val2)
x_test = testdata.iloc[:, [3, 4, 5]].values
x_test

array([[ 8.        ,  1.        ,  1.        ],
       [49.        ,  0.        ,  0.        ],
       [29.69477528,  0.        ,  0.        ],
       [24.        ,  2.        ,  1.        ],
       [36.        ,  0.        ,  0.        ],
       [71.        ,  0.        ,  0.        ],
       [16.        ,  0.        ,  0.        ],
       [29.69477528,  0.        ,  0.        ],
       [18.        ,  0.        ,  0.        ],
       [29.69477528,  0.        ,  0.        ],
       [63.        ,  1.        ,  0.        ],
       [29.69477528,  0.        ,  0.        ],
       [24.        ,  0.        ,  0.        ],
       [23.        ,  0.        ,  0.        ],
       [71.        ,  0.        ,  0.        ],
       [21.        ,  1.        ,  0.        ],
       [21.        ,  0.        ,  0.        ],
       [ 4.        ,  1.        ,  1.        ],
       [22.        ,  0.        ,  0.        ],
       [18.        ,  0.        ,  0.        ],
       [29.69477528,  1.        ,  0.   

In [40]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0], dtype=int64)

In [41]:
np.savetxt(r"C:\Users\aryac\notebook materials\titanic_prediction.csv", y_pred, delimiter=",")