### Importing in Python

In [2]:
import math
math.sqrt(16)

4.0

In [5]:
import math as arya
arya.sqrt(10)

3.1622776601683795

<i>Python arrays/lists in general are a little slow </i>(since it can store anything technically).
<i>but we can specify the type of list/array</i>
<br>
<b>Numpy arrays store homogeneous data. </b>(most of the code is written in C language).

## Numpy

In [6]:
import numpy as np

In [9]:
l=[1,3,"2"]
# it converts the "2" to int type
np.array(l)

array(['1', '3', '2'], dtype='<U11')

In [15]:
np.ones(10)
# array with 10, 1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
a=np.zeros(5)
a.dtype
# why the 'dots'

dtype('float64')

In [20]:
a=np.zeros(5, int)
a.dtype

dtype('int32')

In [23]:
# instead of int, we can pass a tuple for 2D arrays

np.zeros((4,3)) # row, col

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
# 3D array
np.zeros((4,3,2), int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [30]:
# accessing and changing data
a=np.ones((2,3), int)
a[1]=23
a

array([[ 1,  1,  1],
       [23, 23, 23]])

In [34]:
# slicing
a=np.ones(6, int)
# 1, 1, 1, 34, 1, 1
a[3]=34
a[2:5]

array([ 1, 34,  1])

In [41]:
a=np.ones((2,3), int)
a.shape

(2, 3)

In [46]:
a=np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(a[1])

[4 5 6]


In [48]:
a=np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
a[0:2, 0]
# shows 0th and 1st row and 0th column

array([1, 4])

In [50]:
a[:, 0]

array([ 1,  4,  7, 10])

In [52]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Numpy operations

In [53]:
a=np.array([1,2,3])
b=np.array([7,8,9])

a+2
# adds 2 to every element

array([3, 4, 5])

In [55]:
a=np.array([1,2,3])
b=np.array([7,8,9])
print(a+b)

[ 8 10 12]


In [56]:
a.mean()

2.0

In [57]:
a.sum()

6

In [64]:
a=np.array([3,4])
b=np.array([0,0])

sq_d=((a-b)**2)
ans=np.sqrt(sq_d.sum())
ans

# distance from (0, 0) to (3, 4)

5.0

In [70]:
a=np.array([1, 2, 3, 4, 6, 7, 9, 11])
m=a.mean()
((a-m)**2).sum()

85.875

In [76]:
# dot product

a=np.array([[1,2],[3,4]])
b=np.array([[10,20],[30,40]])

a.dot(b)

array([[ 70, 100],
       [150, 220]])

In [77]:
np.sum([[0, 1], [0, 5]], axis=1)

array([1, 5])

##### there are numpy matrices too!!