In [1]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
iris = datasets.load_iris()
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size = 0.25)

In [3]:
# we are using Linear regression
clf = LinearRegression()
cross_val_score(clf, x_train, y_train, cv = KFold(n_splits = 3, shuffle = True, random_state = None))

array([0.92323541, 0.90422204, 0.86926016])

In [4]:
clf = LinearRegression()
cross_val_score(clf, iris.data, iris.target, cv = KFold(n_splits = 3, shuffle = False, random_state = None))
# no checking data

array([0., 0., 0.])

In [5]:
clf = LinearRegression()
cross_val_score(clf, iris.data, iris.target, cv = KFold(n_splits = 3, shuffle = True, random_state = None))

array([0.9131146 , 0.94334799, 0.91720235])