In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('international-airline-passengers.csv', usecols = [1])
df

values
0       112
1       118
2       132
3       129
4       121
..      ...
139     606
140     508
141     461
142     390
143     432

[144 rows x 1 columns]

In [3]:
df.describe()

values
count  144.000000
mean   280.298611
std    119.966317
min    104.000000
25%    180.000000
50%    265.500000
75%    360.500000
max    622.000000

In [4]:
values = df.values.astype('float32')
values

array([[112.],
       [118.],
       [132.],
       [129.],
       [121.],
       [135.],
       [148.],
       [148.],
       [136.],
       [119.],
       [104.],
       [118.],
       [115.],
       [126.],
       [141.],
       [135.],
       [125.],
       [149.],
       [170.],
       [170.],
       [158.],
       [133.],
       [114.],
       [140.],
       [145.],
       [150.],
       [178.],
       [163.],
       [172.],
       [178.],
       [199.],
       [199.],
       [184.],
       [162.],
       [146.],
       [166.],
       [171.],
       [180.],
       [193.],
       [181.],
       [183.],
       [218.],
       [230.],
       [242.],
       [209.],
       [191.],
       [172.],
       [194.],
       [196.],
       [196.],
       [236.],
       [235.],
       [229.],
       [243.],
       [264.],
       [272.],
       [237.],
       [211.],
       [180.],
       [201.],
       [204.],
       [188.],
       [235.],
       [227.],
       [234.],
       [264.],
       [30

In [5]:
values.shape

(144, 1)

In [6]:
train_size = (int)(values.shape[0] * 0.67)
train_size

96

In [7]:
test_size = values.shape[0] - train_size

In [8]:
train_data = values[0:train_size]
train_data

array([[112.],
       [118.],
       [132.],
       [129.],
       [121.],
       [135.],
       [148.],
       [148.],
       [136.],
       [119.],
       [104.],
       [118.],
       [115.],
       [126.],
       [141.],
       [135.],
       [125.],
       [149.],
       [170.],
       [170.],
       [158.],
       [133.],
       [114.],
       [140.],
       [145.],
       [150.],
       [178.],
       [163.],
       [172.],
       [178.],
       [199.],
       [199.],
       [184.],
       [162.],
       [146.],
       [166.],
       [171.],
       [180.],
       [193.],
       [181.],
       [183.],
       [218.],
       [230.],
       [242.],
       [209.],
       [191.],
       [172.],
       [194.],
       [196.],
       [196.],
       [236.],
       [235.],
       [229.],
       [243.],
       [264.],
       [272.],
       [237.],
       [211.],
       [180.],
       [201.],
       [204.],
       [188.],
       [235.],
       [227.],
       [234.],
       [264.],
       [30

In [9]:
test_data = values[train_size:]
test_data

array([[315.],
       [301.],
       [356.],
       [348.],
       [355.],
       [422.],
       [465.],
       [467.],
       [404.],
       [347.],
       [305.],
       [336.],
       [340.],
       [318.],
       [362.],
       [348.],
       [363.],
       [435.],
       [491.],
       [505.],
       [404.],
       [359.],
       [310.],
       [337.],
       [360.],
       [342.],
       [406.],
       [396.],
       [420.],
       [472.],
       [548.],
       [559.],
       [463.],
       [407.],
       [362.],
       [405.],
       [417.],
       [391.],
       [419.],
       [461.],
       [472.],
       [535.],
       [622.],
       [606.],
       [508.],
       [461.],
       [390.],
       [432.]], dtype=float32)

In [10]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range = (0, 1))
train_data = scaler.fit_transform(train_data)
test_data = scaler.transform(test_data)

In [11]:
def create_dataset(data, k) :
    dataX, dataY = [], []
    for i in range(data.shape[0]-k) :
        x = data[i:i+k, 0]
        y = data[i+k, 0]
        dataX.append(x)
        dataY.append(y)
    return np.array(dataX), np.array(dataY)

In [12]:
look_back = 12
trainX, trainY = create_dataset(train_data, look_back)
testX, testY = create_dataset(test_data, look_back)

In [13]:
trainX = np.reshape(trainX, (trainX.shape[0], look_back, 1))
testX = np.reshape(testX, (testX.shape[0], look_back, 1))

In [14]:
from keras.models import Sequential
from keras.layers import SimpleRNN, Dense

In [15]:
model = Sequential()
model.add(SimpleRNN(4, input_shape = (look_back, 1)))
model.add(Dense(1))

In [16]:
model.compile(loss = 'mean_squared_error', optimizer = 'adam')

In [17]:
model.fit(trainX, trainY, epochs = 10, batch_size = 1)

Epoch 1/10
84/84 [==============================] - 2s 7ms/step - loss: 0.0430
Epoch 2/10
84/84 [==============================] - 0s 5ms/step - loss: 0.0196
Epoch 3/10
84/84 [==============================] - 0s 5ms/step - loss: 0.0175
Epoch 4/10
84/84 [==============================] - 0s 5ms/step - loss: 0.0156
Epoch 5/10
84/84 [==============================] - 0s 4ms/step - loss: 0.0151
Epoch 6/10
84/84 [==============================] - 0s 5ms/step - loss: 0.0131
Epoch 7/10
84/84 [==============================] - 0s 6ms/step - loss: 0.0125
Epoch 8/10
84/84 [==============================] - 0s 6ms/step - loss: 0.0113
Epoch 9/10
84/84 [==============================] - 1s 7ms/step - loss: 0.0111
Epoch 10/10
84/84 [==============================] - 0s 5ms/step - loss: 0.0101


In [18]:
test_predict = model.predict(testX)
test_predict = scaler.inverse_transform(test_predict).ravel() # ravel means to make 1D array
test_predict

array([340.91824, 316.37817, 289.86676, 347.36523, 326.2012 , 323.17615,
       382.99225, 397.3912 , 390.64258, 337.771  , 338.65686, 324.94662,
       338.1679 , 331.5784 , 305.95096, 367.20392, 349.89944, 356.02695,
       394.42545, 420.464  , 412.03873, 366.2241 , 354.9452 , 346.80356,
       376.9859 , 361.11362, 334.63428, 371.69067, 392.40372, 379.69666,
       412.19934, 440.84244, 424.908  , 385.82892, 379.2431 , 349.9061 ],
      dtype=float32)